config/routes.rb
Corneroffice::Application.routes.draw do
  resource :user, :only => [:new, :create, :edit, :update]
  resource :session, :only => [:new, :create, :destroy]

  root :to => "homepage#show"
end

app/models/user.rb
class User < ActiveRecord::Base
  include SimplestAuth::Model
  authenticate_by :email

  attr_accessible :email, :name, :password, :password_confirmation, :highrise_access_token

  validates :name, :presence => true
  validates :email, :presence => true, :uniqueness => true, :email => true
  validates :highrise_access_token, :presence => true
  validates :password, :confirmation => true
  validates :password, :length => { :minimum => 5 }, :if => :password_required?
  validates :password, :presence => true, :on => :create
  validates :password_confirmation, :presence => true, :on => :create

  def set_highrise_info(info)
    self.email = info.email_address
    self.name = info.name
  end

  def set_token(token_options)
    update_attribute(:highrise_access_token, Highrise::AccessToken.new(token_options).token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SimplestAuth::Controller
  
  private

  def set_highrise_access_token
     Highrise::Base.oauth_token = current_user.highrise_access_token
  end

  def token_options
    {
    :client_secret => Highrise::ClientSecret,
    :client_id     => Highrise::ClientId,  
    :redirect_uri  => "http://corneroffice.dev/user/new",
    }
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
    @token = Highrise::AccessToken.new(token_options)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.authenticate(session_params[:email], session_params[:password])
    if user
      self.current_user = user
      redirect_to root_path, :alert => "Signed in successfully"
    else
      redirect_to new_session_path, :alert => "Couldn't locate a user with those credentials"
    end
  end

  def destroy
    self.current_user = nil
    redirect_to new_session_path, :alert => "Signed out"
  end

  private

  def session_params
    params[:session] || {}
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :load_user, :only => [:new, :edit, :update]
  before_filter :auth_code_missing_failure, :unless => :auth_code_present?, :only => :new
  before_filter :set_highrise_access_token, :unless => :highrise_access_token_present?, :only => :new

  def new
    set_highrise_access_token

    begin
      @user.set_highrise_info(Highrise::User.me)
    rescue
      flash.now[:notice] = "We couldn't retrieve your information from Highrise at this time."
    end
  end

  def create
    @user = User.new params[:user]

    if @user.save
      redirect_to root_path, :notice => "You're signed up!"
    else
      signup_fail_with_message
    end
  end
  
  private

  def load_user
    @user = current_user || User.new
  end

  def signup_fail_with_message(msg = "There were errors with your submission.")
    flash.now[:error] = msg
    render :new and return
  end

  def auth_code_missing_failure
    signup_fail_with_message "No authorization code was provided."
  end

  def auth_code_present?
    params[:code].present?
  end

  def highrise_access_token_present?
    @user.highrise_access_token.present?
  end

  def set_highrise_access_token
    begin
      @user.set_token(token_options.merge(:authorization_code => params[:code]))
      self.current_user = @user
    rescue
      signup_fail_with_message "Invalid authorization code. Try again."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/homepage/show.html.erb
<h1>Corner Office</h1>
<%= link_to "Sign Up with Highrise", @token.authorize_url %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Corneroffice</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= link_to "Sign Out", session_path, :method => :delete %>
<%= link_to "Sign In", new_session_path %>

<% flash.each do |key, value| %>
      <% if [:error, :notice, :alert].include?(key) && value.present? %>
        <div class="alert <%= key %>">
          <%= value %>
        </div>
      <% end %>
    <% end %>
<%= yield %>

</body>
</html>

app/views/users/invalid_token.html.erb
<h1>Sign Up</h1>
<h2>Whoops.</h2>
<h3>We couldn't get a valid token. Please try integrating with Highrise again.</h3>
<%= link_to "Sign Up with Highrise", @token.authorize_url %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
<%= simple_form_for @user, :url => user_path, :method => :post do |f| %>
  <%= f.input :name %>
  <%= f.input :email %>
  <%= f.input :password %>
  <%= f.input :password_confirmation %>
  <%= f.input :highrise_access_token, :as => :hidden %>
  <%= f.button :submit, :value => "Sign Up" %>
<% end %>

app/views/users/new_without_code.html.erb
<h1>Sign Up</h1>
<h2>Whoops.</h2>
<h3>Please sign up through Highrise first.</h3>
<%= link_to "Sign Up with Highrise", @token.authorize_url %>